server:
  port: 9999

#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: proxy_route
#          uri: https://icanhazdadjoke.com
#          predicates:
#            - Path=/api/tardis-proxy/**
#          filters:
#            - RewritePath=/api/tardis-proxy, /

